<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
* @file
* Customizations for the University of Manitoba Islandora distribution.
*/

/**
 * Implements hook_help().
 */
function manitoba_custom_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    case 'help.page.manitoba_custom':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Manitoba Custom provides customizations for the University of Manitoba Drupal distribution.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements THEME_preprocess_HOOK() for mirador templates.
 */
function manitoba_custom_preprocess_mirador(&$variables) {
  if (isset($variables['mirador_view_id']) &&
    isset($variables['#attached']['drupalSettings']['mirador']['viewers']['#' . $variables['mirador_view_id']])) {
    $config = &$variables['#attached']['drupalSettings']['mirador']['viewers']['#' . $variables['mirador_view_id']];
    $config['window']['allowClose'] = FALSE;
    $config['workspaceControlPanel']['enabled'] = FALSE;
    // $config['window']['defaultView'] = 'book';
  }
}
