<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\NodeInterface;
use Drupal\views\ViewExecutable;

/**
* @file
* Customizations for the University of Manitoba Islandora distribution.
*/

/**
 * Implements hook_help().
 */
function manitoba_custom_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    case 'help.page.manitoba_custom':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Manitoba Custom provides customizations for the University of Manitoba Drupal distribution.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements THEME_preprocess_HOOK() for mirador templates.
 */
function manitoba_custom_preprocess_mirador(&$variables) {
  if (isset($variables['mirador_view_id']) &&
    isset($variables['#attached']['drupalSettings']['mirador']['viewers']['#' . $variables['mirador_view_id']])) {
    $config = &$variables['#attached']['drupalSettings']['mirador']['viewers']['#' . $variables['mirador_view_id']];
    // Removes the ability to close the window.
    $config['window']['allowClose'] = FALSE;
    // Make text not selectable
    $config['window']['textOverlay']['selectable'] = FALSE;
    // Removes workspace control panel
    $config['workspaceControlPanel']['enabled'] = FALSE;
    // Customize the search highlight colors. These colours are not good, change before implementing.
    //$config['theme']['palette']['search'] =
    //  [
    //    'default' => ['fillStyle' => '#cc0000', 'globalAlpha' => 0.5],
    //    'selected' => ['fillStyle' => '#ccee00', 'globalAlpha' => 0.6]
    //  ];
    // Change the default view to book view. Not a great idea, but just marks where the option is.
    // $config['window']['defaultView'] = 'book';
    // This takes the search term from the query string and passes it into Mirador's config.
    $search_term = \Drupal::request()->query->get('search_hocr');
    if ($search_term) {
      $config['windows'][0]['defaultSearchQuery'] = $search_term;
    }
    // Make sure the cache accounts for the search term when caching the page.
    $variables['#cache']['contexts'][] = 'url.query_args:search_hocr';
  }
}

/**
 * Implements hook_form_alter().
 */
function manitoba_custom_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Alter the search form to add a placeholder and change the button text.
  if ($form_id == 'openid_connect_login_form') {
    $form['openid_connect_client_generic_login']['#value'] = t('Log in with your U Manitoba Account');
  }
}

/**
 * Implements hook_views_pre_render().
 */
function manitoba_custom_views_pre_render(ViewExecutable $view) {
  if ($view->id() == 'iiif_manifest' && $view->current_display == 'rest_export_intermediate') {
    if (!empty($view->result)) {
      $row = $view->result[0];
      $title_handler = $view->field['title'];
      $title = manitoba_custom_views_first_string($title_handler->getValue($row));
      $date_handler = $view->field['field_edtf_date_issued'];
      $date = manitoba_custom_views_first_string($date_handler->getValue($row));
      if (!empty($date)) {
        $title .= " - $date";
      }
      $view->setTitle($title);
      $view->display_handler->setOption('page_title', $title);
    }
  }
  else if ($view->id() == 'solr_search_content' && $view->current_display == 'solr_search_page_1') {
    // Only operate on the search results page.
    $term = $view->getExposedInput()['a'] ?? null;
    if (is_array($term)) {
      $term = reset($term);
      if (is_array($term) && isset($term['v'])) {
        $term = $term['v'];
      }
    }
    if (empty($term)) {
      // Only continue if there is a search term.
      return;
    }

    $field_id = 'title';
    if (isset($view->field[$field_id])) {
      $view->field[$field_id]->options['alter']['make_link'] = true;
      $view->field[$field_id]->options['alter']['query'] = [
        'search_hocr' => $term,
      ];
    }
  }
}

function manitoba_custom_views_first_string($value) {
  if (!is_array($value)) {
    return $value;
  }
  if (isset($value[0]['#markup'])) {
    return $value[0]['#markup'];
  }
  if (isset($value[0]['value'])) {
    return $value[0]['value'];
   }
  foreach ($value as $item) {
    if (is_string($item)) {
      return $item;
    }
    if (is_array($item)) {
      foreach ($item as $sub) {
        if (is_string($sub)) {
          return $sub;
        }
      }
    }
  }
  return '';
}

/**
 * Implements hook_ENTITY_TYPE_presave()
 */
function manitoba_custom_node_presave(NodeInterface $node) {
  if (
    !\Drupal::moduleHandler()->moduleExists('pathauto') ||
    !$node->hasField('path')
  ) {
    return;
  }
  $config = \Drupal::config('manitoba_custom.settings');
  $field_name = $config->get('pathauto_field_name');
  $bundle_name = $config->get('pathauto_bundle_name');

  if ($node->bundle() !== $bundle_name) {
    return;
  }
  if (!$node->hasField($field_name) || $node->get($field_name)->isEmpty()) {
    return;
  }

  $skip_terms = $config->get('pathauto_skipped_models') ?? [];
  foreach ($node->get($field_name)->referencedEntities() as $term) {
    if (in_array($term->id(), $skip_terms)) {
      // 0 is the same as PathautoState::SKIP, but avoids the dependency on pathauto.
      $node->get('path')->pathauto = 0;
      break;
    }
  }
}
